### PR TITLE
Initial eploration of metrics

### PR DESCRIPTION
**Pull request by juliuscc**

### CODE REVIEW

**Comment by hannesrabo** [comment]
We are not using the `regex` param in `get_line_with_find`. Maybe add that?

**Comment by juliuscc** [comment]
Good catch Hannes

**Comment by juliuscc** [comment]
fixed

**Comment by hannesrabo** [comment]
In this case
`data_lines = list(filter(lambda line: regex_pattern.match(line), body))`
I don't think that the lambda is necessary. It should be possible to just write:
`data_lines = list(filter(regex_pattern.match, body))`

**Comment by juliuscc** [comment]
also fixed :)

**Comment by hannesrabo** [comment]
This is very nice: `metrics_df_node1['ReadThroughput'] = metrics_df_node1['ReadCount'] - metrics_df_node1['ReadCount'].shift(1)` This looks much better than it would do in R.

I assume that it uses 0 for the first value that is now empty after shifting?

I really like the throughput graph as well. It is great that we can create something this exact!

The readLatency graph should be dropped I think

**Comment by hannesrabo** [comment]
> I assume that it uses 0 for the first value that is now empty after shifting?

This does not appear to be the case. It creates a NaN value for the first number. Maybe fix, but it is not necessary as we aren't loosing a lot of data regardless.

**Comment by hannesrabo** [comment]
Great job! Now we only have to start to look at the percentile values as well 🙂

**Comment by juliuscc** [comment]
I added now that nan -> 0

**Pull request merged**
